# More Exceptions

## HackerRank 30 Day Code Challenge Day 17

HackerRank is a technology company that provides a platform for competitive programming challenges and technical interviews. 
It was founded in 2009 and is headquartered in Mountain View, California.

### Features

- Code Challenges
- Practice
- Contest 
- Interview Preparation
- Skill Certification
- Hiring

### Objective

Yesterday's challenge taught you to manage exceptional situations by using try and catch blocks. In today's challenge, you will practice throwing and propagating an exception. 

### Task

Write a Calculator class with a single method: int power(int,int). The power method takes two integers,  n and  p, as parameters and returns the integer result of n to the power of p . If either  n or p is negative, then the method must throw an exception with the message: n and p should be non-negative.

### Input Format

Input from stdin is handled for you by the locked stub code in your editor. The first line contains an integer, T, the number of test cases. Each of the  T subsequent lines describes a test case in  2 space-separated integers that denote  n and p, respectively.

### Output Format

Output to stdout is handled for you by the locked stub code in your editor. There are T  lines of output, where each line contains the re

Given an integer, n , print its first 10 multiples. Each multiple n x i  (where i>=1 && i<=10 ) should be printed on a new line in the form: n x i = result.
